version: 2.1
jobs:
  build-node-lts:  &common-build
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  build-node10:
    <<: *common-build
    docker:
      - image: circleci/node:10

  build-node8:
    <<: *common-build
    docker:
      - image: circleci/node:8

  build-node6:
    <<: *common-build
    docker:
      - image: circleci/node:6

  sonar:
      working_directory: ~/repo
      machine:
        enabled: true
      steps:
        - attach_workspace:
            at: ~/repo
        - run:
            name: Pull sonar image
            command: |
              echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
              docker pull pagarme/sonar-scanner
        - run:
            name: Run Sonar
            command: |
              sudo sed -i 's/\/home\/circleci\/repo\//\/usr\/src\//g' coverage/lcov.info
              docker run -ti -v $(pwd):/usr/src/ pagarme/sonar-scanner -Dsonar.branch.name=$CIRCLE_BRANCH

  update-docs:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - add_ssh_keys
      - run: yarn
      - run: git config --global user.email "github-bot@pagar.me"
      - run: git config --global user.name "github-pages[bot]"
      - run: npm run predocs:bump
      - run: npm run docs:bump

  publish-npm:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: yarn
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      # - run: npm publish

workflows:
    build:
      jobs:
        - build-node-lts
        # - sonar:
        #     context: dockerhub
        #     requires:
        #       - build-node-lts
        - build-node10
        - build-node8
        - build-node6

    publish:
      jobs:
        - publish-npm:
            filters:
              tags:
                only: /^([0-9]+).([0-9]+).([0-9]+)$/
              branches:
                ignore: /.*/
        - update-docs:
            requires:
              - "publish-npm"
            filters:
              tags:
                only: /^([0-9]+).([0-9]+).([0-9]+)$/
              branches:
                ignore: /.*/

